import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

// Components
export default function Home() {
  return (
    <div>
      <Head>
        <title>Next with Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col w-full min-h-[100vh]">
        <Navbar />
        <main className="grow flex items-center bg-yellow-300">
          <div className="container-1200 px-5 py-10">
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-black sm:w-7/12 md:w-8/12 text-gray-900">
              Next JS with Tailwind Config Starter Pack
            </h1>
            <p className="text-lg md:text-xl sm:w-7/12 md:w-6/12 py-5">
              A simple Next JS template/Starter Pack with the Tailwind
              configuration to save you time.
            </p>
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
}
